version: '3.6'

services:
  backend:
    container_name: diamante
    build: ./
    command: npm start
    working_dir: /usr/src/diamante
    ports:
      - 5000:5000 #Development
      - 80:5000 #Production
      - 443:5000 #Production
    env_file:
      - server.env
    links:
      - postgres
      - redis
    volumes:
      - ./package.json:/usr/src/diamante/package.json
      - ./package-lock.json:/usr/src/diamante/package-lock.json
      - ./dist:/usr/src/diamante/dist
      - ./config:/usr/src/diamante/config
      - ./lib/client/build:/usr/src/diamante/build

  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - 5432:5432
    env_file:
      - pg.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379